---
#Make sure server is availabe and service is not running

  - name:  ping all servers
    ping:

    - name: Remove Tomcat10 from centos
    file:
      path: /opt/tomcat10
      state: absent
    when: ansible_distribution == "CentOS"

  - name: Do some stuff on centos
    command: "sh sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
    when: ansible_distribution == "CentOS"

  - name: Stop Tomcat
    command: sh /opt/tomcat8/bin/shutdown.sh

  - name: Remove Tomcat
    file:
      path: /opt/tomcat8
      state: absent

  - name: remove user "tomcat"
    user:
      name: tomcat
      state: absent

  - name: remove group "tomcat"
    group:
      name: tomcat
      state: absent